### ISSUE TITLE
ToDo - List

### ISSUE THREAD

**Issue by VoltanaDMG** [VoltanaDMG/scg3_v2019#1]
## ToDo - Liste

- [x] Upload .obj - Models
- [x] CI pipeline - Automatic builds (only AppVeyor Win32 | x64)
- [ ] Documentation `scg3` (outdated)
--- 
- [ ] TransformAnimations (min. one Animation)
- [ ] Mouse- / Keyboard-Interactions
--- 
- [ ] Materials
- [ ] Textures
---
- [ ] Shading 
- [ ] Lightning (min. two lights)
---
- [ ] Shell- / Bash-Script
- [ ] Documentation

**Comment by VoltanaDMG** [comment]
--- Finn
There are problems while building the `scg3` at Linux (Ubuntu 14.x.x). CMake is saying that it can't find any of those files:
```
- glfw3Config.cmake
- glfw3-config.cmake
```

This command is required to build `glfw3` from source:
`cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu`

---

```bash
# GLFW 3.1.1 install
wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
unzip glfw-3.2.1.zip
cd glfw-3.2.1
cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
make
sudo make install
cd ..
```

**Comment by Xemorph** [comment]
> --- Finn
There are problems while building the scg3 at Linux (Ubuntu 14.x.x). CMake is saying that it can't find any of those files:
>```
>- glfw3Config.cmake
>- glfw3-config.cmake
>```

This is just a problem with the apt packages, they aren`t delivering the CMake config files at some distributions. As a solution we can say that GLFW is a requirement which needs to be builded at a developer machine.

This would be definitly the easiest way....

**Comment by VoltanaDMG** [comment]
Okay, we can dig into it later when we're building the CI pipeline for TravisCI.
The CI pipeline for `AppVeyor` is working now. But it should cleaned up and refactored to support Win32 and x64. Also `msbuild` should replaced with `CMake` to get one structure.
